# Generated by Django 3.2 on 2021-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture'),
        ),
    ]
