# Generated by Django 3.2 on 2021-05-05 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210505_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
